requirements/_testing.txt, stagecraft/apps/dashboards/migrations/0007_consistent_group_by_array.py, stagecraft/apps/dashboards/models/module.py, stagecraft/apps/dashboards/tests/models/test_module.py, stagecraft/libs/schemas/schemas.py
Data migration — make group_by consistently a list
This makes it easier for clients to work with. In particular, languages
like Go which are statically-typed.
Rewrite group_by to be a list when writing to DB
Also bump pep8 to support long URLs in comments, and make related pep8
changes.
See https://www.agileplannerapp.com/boards/15088/cards/9043
=> Make group_by consistently a list

stagecraft/apps/datasets/migrations/0014_auto__chg_field_datatype_name.py, stagecraft/apps/datasets/models/data_type.py
This is due to running transform migrations. We want to create a
transform type for the module
g-cloud/proportion-of-sales-from-small-and-medium-enterprises
and use the module slug as the data type name. This is 53 characters,
but setting the limit to 60 chars as it is a round number and shouldnt
hit the limit on mongo collection names which is 128 characters
=> Increase size of datatype name field

tools/replicate-db.sh
The stagecraft user on the dev vm needs to be able to create a database
for the test runs, the permissions the user has copied down from
preview/staging/prod does not allow it to do this.
=> Add superuser to stagecraft on dev vm

stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/tests/views/test_transactions_explorer.py, stagecraft/apps/dashboards/views/transactions_explorer.py, stagecraft/urls.py
In order to map data from the transactions explorer dataset to the
relevant dashboard slug we need to be able to pass in a service id
and get back dashboards that use it.
The mapping from a service_id to a dashboard should be 1 to 1 as
dashboards are meant to represent services. There are unpublished
dashboards that use data for services for playing around/testing so we
filter these out to avoid making the wrong decision.
=> Route to get dashboards by tx service id

create_tx_transform.py
When we run it we set the start to the earliest possible timestamp in
transactions explorer and the end at to significantly after the latest.
This ensure we will collect the latest data.
In doing this we realised the transform needs to ensure it gets the
latest non null value or null if none and posts it - currently it will
overwrite with nulls.
Tested and working on dev vm.
Relies on https://github.com/alphagov/backdrop/pull/412 to work
=> Creates transform type and transform for tx, runs it

stagecraft/apps/datasets/views/data_set.py, stagecraft/libs/views/resource.py
A small optimisation in order to speed up the retrieval of all data sets through the GET /data-sets endpoint.
This optimisation is in support of a usability improvement to the Performance Platform admin tool which requires that the admin tool makes use of the /data-sets endpoint for the first time - see https://github.com/alphagov/performanceplatform-admin/tree/select-groups-and-types  and https://www.agileplannerapp.com/boards/15088/cards/8879.
By using Django's select_related QuerySet method to eager load the data group and type associations for each data set, the overall query count is reduced significantly. This in turn reduces the time taken to retrieve all data sets. In development, the time taken to retrieve all data sets was observed to drop from circa 3.5 seconds to circa 1.2 …
=> Eager load associations to speed up GET /data-sets

stagecraft/tools/spreadsheets.py, stagecraft/tools/test_spreadsheet.py, stagecraft/tools/txex-migration.py
This pull request fixes the spreadsheet parsing and merging for the changed column positions in the new names spreadsheet. It makes this more configureable to guard against future changes and makes the test pass independently of the configuration changes needed for the actual spreadsheet. It still uses column positions however when arguably using key based parsing (with the column headers as keys) would be more robust. If the spreadsheet keeps changing perhaps this would be a good further refactoring to carry out.
=> Fix spreadsheet parsing

stagecraft/apps/datasets/tests/views/test_data_set.py, stagecraft/libs/views/resource.py
Allow users with the common dashboard-editor role to see all datasets. This is
required for the admin app to show users a list of dataset groups and
types in a dropdown list.
Although this is part of the base resource view, this should not affect
endpoints other than datasets as they are the only models that have the
backdrop_user relationship which is used for filtering.
=> Allow 'dashboard-editor' users to see all datasets

stagecraft/tools/import_dashboards.py, stagecraft/tools/spreadsheets.py, stagecraft/tools/test_spreadsheet.py
This loads all records from the transactions explorer feed and,
depending on the data present, creates modules and a dashboard.
https://www.agileplannerapp.com/boards/15088/cards/9254
This also gives us a base to build on for updating all existing dashboards
from the feed. The spreadsheet merge test is disabled until we
need merge functions.
Overall this is fairly low-quality code, but it should suffice as a first iteration
for creating dashboards.
=> Create low volume dashboards from transactions explorer feed

requirements/_common.txt, stagecraft/apps/dashboards/models/module.py, stagecraft/apps/dashboards/views/dashboard.py, stagecraft/settings/common.py
We have noticed a number of requests resulting in a 502 error because stagecraft
is timed out by gunicorn. This is usually requesting the config for an individual
dashboard. Profiling this endpoint showed a lot of queries being generated - the
change to the module manager reduces this significantly. This also adds some 
timings to that endpoint, and uses dogslow to give a stack trace of a slow request
=> fix / more diagnostics for slow dashboard endpoint

stagecraft/wsgi.py
The stats will be written to the gunicorn error file, which makes it easy to 
check when processes have been killed.
=> Add gc stats

.travis.yml, run_tests.sh, stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/models/module.py, stagecraft/apps/transforms/admin.py, stagecraft/libs/timing/timer.py, stagecraft/tools/import_dashboards.py, stagecraft/tools/redirects.py, stagecraft/tools/spreadsheets.py, stagecraft/tools/test_import_dashboards.py, stagecraft/tools/test_redirect_generation.py, stagecraft/tools/tests/test_spreadsheet.py, stagecraft/wsgi.py
To help with tracking down the 502 errors on production - some seem to be
hanging during the spotlightify stage. Use a decorator to do the timings
Also stop running autopep8 in travis, dont run it on autogenerated migrations
and fix the pep8 errors
=> Add some more timing information to stagecraft

stagecraft/libs/patches/db.py, stagecraft/libs/timing/timer.py, stagecraft/wsgi.py
This is based on
https://github.com/andymckay/django-statsd/blob/master/django_statsd/patches/db.py
but instead of sending to statsd, send info to the log. Also capture the
query so we can see if certain queries are timing out.
=> Log timing info for db queries

stagecraft/apps/organisation/tests/test_views.py, stagecraft/apps/organisation/views.py, stagecraft/libs/views/resource.py
Currently filtering requires all the filter parameters to be present and it only allows one value for each filter key. This enables passing in multiple values for a key and then filtering by whether any of them are present.
This is being added so we can restrict the drop down for organisation choice in the new sign up - currently services and service groups are also appearing.
=> Allow filtering by any value in list

stagecraft/apps/organisation/tests/test_views.py, stagecraft/apps/organisation/views.py
- using select related goes from around 12 seconds to around 7 with the
production list
- Removing resolve_parents takes us from 7 to lt 1.
- this is a functional change but Tom assures me this is not
used anywhere (and is not currently correct as it only resolves a
single parent.)
=> Speed up the org list api

stagecraft/libs/request_logger/middleware.py, stagecraft/settings/development.py, stagecraft/settings/production.py
For tracing the 502 errors we are seeing.
From kibana, we can trace an nginx 502 with a request-id to a single log
line in stagecraft, which is when the request processing is started.
From here we can get a process_id, but it is impossible to work out
which log lines refer to the same request as a process can handle
multiple requests.
This uses the idea in
https://raw.githubusercontent.com/jedie/django-tools/master/django_tools/middlewares/ThreadLocal.py
to store the request in a thread local variable, which we can then
reference when logging
=> Add a request-id to all log messages

stagecraft/libs/request_logger/middleware.py
Using __dict__ is unpythonic - the example in
https://docs.python.org/3/howto/logging-cookbook.html assigns to
properties on the logrecord
I thought I had tried this yesterday and it didnt work...
=> Stop using the dict

stagecraft/apps/dashboards/migrations/0011_auto__add_field_dashboard_department_cache__add_field_dashboard_agency.py, stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/tests/models/test_dashboard.py, stagecraft/apps/organisation/views.py, stagecraft/tools/import_dashboards.py, stagecraft/tools/load_organisations.py, stagecraft/tools/spreadsheets.py, stagecraft/tools/tests/test_import_dashboards.py, stagecraft/tools/tests/test_load_organisations.py, stagecraft/tools/tests/test_redirect_generation.py
This improves the organisation loading code and
updates it against the latest spreadsheet loading code.
It also improves dashboard loading and increases the
length of the title field.
Denormalised fields have been added to dashboards to
improve the loading of /public/dashboards.
This also fixes query parameters for the quarterly
and digital takeup modules.
Django emulates CASCADE which will delete dashboards associated
to organisations when the the organisation is deleted.
Prevent this from happening by setting foreign keys to NULL
beforehand.
=> Improve organisation and dashboard loading/querying

stagecraft/apps/dashboards/migrations/0013_auto__add_field_dashboard_status.py, stagecraft/apps/dashboards/migrations/0014_set_status.py, stagecraft/apps/dashboards/migrations/0015_auto__del_field_dashboard_published.py, stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/tests/factories/factories.py, stagecraft/apps/dashboards/tests/models/test_dashboard.py, stagecraft/apps/dashboards/tests/views/test_dashboard.py, stagecraft/apps/dashboards/views/dashboard.py
Add a status field to the Dashboard model which can hold one of the following values: 'unpublished', 'in-review' or 'published'.
Remove the published field and instead derive its value from the status attribute:
- When status is 'unpublished' or 'in-review', published is False
- When status is 'published', published is True
The published attribute can also be used to set the status field:
- When published is set to True, status is set to 'published'
- When published is set to False, status is set to 'unpublished'
This change is in support of story: https://www.pivotaltracker.com/story/show/89863072
=> Replace the published column with a status column on the Dashboard model

.gitignore, stagecraft/libs/authorization/http.py, stagecraft/settings/development.py, stagecraft/settings/production.py
This modifies the authorisation decorator to record
the user UID and request info (path, method, body).
It writes to a separate file, stagecraft.audit.log.json.
=> Add audit logging for authorised actions

stagecraft/libs/authorization/http.py
We really need to know who it was that was doing an authorized action in
order for the logs to be useful if anything naughty is done.
=> Log out token when outputting audit logs

requirements/_common.txt
As part of upgrading to a supported version, upgrade to the latest
1.6.x, then upgrade to 1.7.x etc.
=> Upgrade to latest 1.6.x django

stagecraft/apps/dashboards/views/module.py, stagecraft/apps/datasets/tests/views/test_data_set.py, stagecraft/apps/datasets/views/data_group.py, stagecraft/apps/datasets/views/data_set.py, stagecraft/apps/organisation/tests/test_views.py, stagecraft/apps/organisation/views.py, stagecraft/libs/views/resource.py, stagecraft/libs/views/tests/test_resource.py, stagecraft/urls.py
Adding a `PUT` endpoint, allowing for better customisation for the id referencing resources (locality and multiple) and splitting up the updating of model fields and the relationships that model has.
=> Improve resource view

stagecraft/apps/dashboards/migrations/0016_fix_module_schemas.py, tools/import_schemas/schema/modules_json/bar_chart_with_number_schema.json, tools/import_schemas/schema/modules_json/grouped_timeseries_schema.json
As part of the work to tighten up the module schemas for stagecraft we've had to create a data migration for the modules.
It would be nice if whoever is going to merge this PR will also run the migration script against preview to verify the updates to the module data is non breaking.
After that we can organise a time to run it against the production dashboard configs.
=> Module migrations for updates schemas

stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/tests/models/test_dashboard.py
Previously it was assumed that all agencies must
be owned by a department, and would result in
a ValueError when trying to retrieve a related
dashboard. But in certain cases (e.g. HMRC) there
is no owning department. This removes the
restriction.
=> Permit agencies to have no owning department

import_schemas.py
If a dashboard / module isn’t valid according to a schema, tell the
user which one failed.
=> Capture details about validation failures

tools/import_schemas/schema/modules_json/completion_rate_schema.json
We have an item in production which has this, so we should allow it.
=> Add optional date-picker to completion rate

stagecraft/apps/dashboards/models/module.py, stagecraft/apps/dashboards/tests/models/test_module.py, stagecraft/apps/dashboards/tests/views/test_dashboard.py, stagecraft/apps/dashboards/tests/views/test_module.py, stagecraft/apps/dashboards/views/dashboard.py, stagecraft/apps/dashboards/views/module.py, stagecraft/apps/datasets/tests/views/test_data_group.py, stagecraft/apps/datasets/tests/views/test_data_set.py, stagecraft/apps/datasets/views/data_group.py, stagecraft/apps/datasets/views/data_set.py, stagecraft/apps/organisation/views.py, stagecraft/apps/transforms/views.py, stagecraft/apps/users/tests/views/test_user.py, stagecraft/apps/users/views.py, stagecraft/libs/authorization/http.py, stagecraft/libs/authorization/tests/test_http.py, stagecraft/libs/views/resource.py, stagecraft/libs/views/tests/test_resource.py, stagecraft/urls.py
The aim is to enforce authorization on routes in one place through the ResourceView base class. To be able to do that, all views need to inherit from ResourceView.
The following views were updated to follow that pattern:
* ModuleType
* Module
* Dashboard
* User
ResourceView also needed updating to allow it to support modules and dashboards:
* Add a PUT method
* Change POST to only create new resources. Previously it was used to create and update.
* Allow the use of a different serialize method for list objects.
* Customise list ordering by passing an order_by field to the GET.
* Standardise how sub_resources are added so that they call methods on the child view. 
https://www.pivotaltracker.com/story/show/93451212
=> Migrate dashboard views to ResourceView

stagecraft/apps/organisation/models.py, stagecraft/apps/organisation/tests/test_models.py, stagecraft/tools/README.md, stagecraft/tools/print_dashboard_ancestors.py, stagecraft/tools/print_node_descendants.py
This adds two scripts: one for printing the
edges from a node to its descendants (using
depth-first search), and one for printing
the edges from a dashboard to its root
ancestor.
These should help us debug issues with the
organisation graph.
=> Add scripts for debugging org structure

stagecraft/libs/authorization/tests/test_http.py
DataSets always require a user. This is not true of all views that
inherit from ResourceView.  Support for Anonymous users was added
during a previous commit to make module dashboard views inherit
from ResourceView:
https://github.com/alphagov/stagecraft/commit/a4b9ad17c64bcbe16b922b87b2509e664ee44bb8
Tests have been added to support this feature.
=> Check permissions for Anonymous Users

stagecraft/tools/import_dashboards.py, stagecraft/tools/import_organisations.py, stagecraft/tools/load_organisations.py
The AppRegistry, new in Django 1.7, requires
setup before it can be used outside of a
django application.
This adds the necessary setup step to our
standalone scripts.
=> Update standalone scripts for Django 1.7

stagecraft/apps/dashboards/tests/views/test_dashboard.py, stagecraft/apps/dashboards/views/dashboard.py, stagecraft/apps/dashboards/views/module.py, stagecraft/apps/datasets/tests/views/test_data_set.py, stagecraft/apps/datasets/views/data_set.py, stagecraft/apps/organisation/views.py, stagecraft/apps/transforms/views.py, stagecraft/libs/authorization/http.py, stagecraft/libs/authorization/tests/test_http.py, stagecraft/libs/views/resource.py, stagecraft/libs/views/tests/test_resource.py, stagecraft/libs/views/utils.py
Remaining bits from the ResourceView migration.
All responses should now be JSON.
=> Support anonymous users and reinstate JSON errors

requirements/_common.txt, requirements/_testing.txt, run_tests.sh, stagecraft/apps/dashboards/migrations/0001_initial.py, stagecraft/apps/dashboards/migrations/0002_auto_20150615_0916.py, stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/models/module.py, stagecraft/apps/datasets/admin/data_group.py, stagecraft/apps/datasets/admin/data_type.py, stagecraft/apps/datasets/migrations/0002_auto_20150609_1959.py, stagecraft/apps/datasets/tests/models/test_data_set.py, stagecraft/apps/organisation/migrations/0001_initial.py, stagecraft/apps/organisation/models.py, stagecraft/apps/transforms/migrations/0001_initial.py, stagecraft/apps/transforms/models.py, stagecraft/apps/users/admin.py, stagecraft/libs/mass_update/test_data_set_mass_update.py
The django_migrations table needs to be updated with an entry for reversion before this PR is deployed in each environment.
The index for date_created on table reversion_revision has been created in all environments.
=> Feature/django 1.8.x

stagecraft/apps/dashboards/views/dashboard.py, stagecraft/apps/dashboards/views/module.py, stagecraft/apps/datasets/views/auth.py, stagecraft/apps/datasets/views/data_group.py, stagecraft/apps/datasets/views/data_set.py, stagecraft/apps/organisation/views.py, stagecraft/apps/transforms/views.py, stagecraft/apps/users/views.py, stagecraft/libs/authorization/http.py, stagecraft/libs/authorization/tests/test_http.py, stagecraft/libs/views/tests/test_resource.py, stagecraft/settings/common.py, stagecraft/settings/development.py
- Define the roles in the common settings file - the roles array is
loosely based on IAM roles used by AWS
- Update and refactor the check_permission method to use sets for the
permission_requested parameter rather than lists
- Update all tests to use sets rather than lists
- Update all views to call the new _get_resource_role_permissions
method rather than explicitly defining the list in each view.
=> Move roles into a centralised location

stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/models/module.py, stagecraft/apps/dashboards/tests/models/test_module.py, stagecraft/apps/dashboards/tests/views/test_dashboard.py, stagecraft/apps/dashboards/tests/views/test_module.py, stagecraft/apps/dashboards/views/module.py, stagecraft/apps/datasets/models/data_set.py, stagecraft/apps/datasets/tests/views/test_data_set.py, stagecraft/apps/transforms/models.py, stagecraft/apps/transforms/tests/factories.py, stagecraft/apps/transforms/tests/test_views.py, stagecraft/libs/views/resource.py
When a resource is created, the user creating it is added to the list of
owners. In the case of dashboards, datasets and transforms the list is
associated to the model directly.
In the case of modules, ownership is delegated to the dashboard the
module is associated with.
The owner is the only non-privileged user who can view and modify their
resources.
This adds various tests and improves testing in places where it was
lacking. Specifically, ownership interactions across resources is
tested, and transforms are better tested.
=> Make the creator of a resource the owner and enforce owner-only access

stagecraft/apps/datasets/tests/views/test_data_set.py, stagecraft/libs/views/resource.py, stagecraft/settings/common.py
- Users with the dashboard editor role should only see their own
dashboards, not all
- Introduced admin and dashboard-editor roles and permissions
See story: https://www.pivotaltracker.com/story/show/97212736
=> Consolidate roles and permissions with Admin App

stagecraft/apps/dashboards/migrations/0004_auto_20150623_1454.py, stagecraft/apps/dashboards/models/dashboard.py, stagecraft/tools/import_dashboards.py, stagecraft/tools/spreadsheets.py, stagecraft/tools/tests/test_import_dashboards.py
Add migrations to increase character limit for slug fields
to handle longer slugs for bis dashboards.
=> If dashboard slug truncated set to original value

stagecraft/tools/import_dashboards.py
Modules of type transactions per quarter are only added to the
dashboard if the transactions per year module type key exists. As
both module types are always added to the dashboard this doesn't
seem to have caused any problems yet, but it has been fixed for
clarity.
=> Update key used to order modules on dashboard.

stagecraft/tools/import_dashboards.py, stagecraft/tools/tests/test_import_dashboards.py
We believe it would be safe to do this for non truncated but it's
probably better to limit it and then perhaps take out the truncated slug
related code after all the data is migrated. As a result the test is
pretty long - it should be okay if we will tidy this up anyway.
=> Updating module query_params to untruncated slug

stagecraft/tools/import_dashboards.py, stagecraft/tools/tests/test_import_dashboards.py
The summaries page will no show these 0s so not having a module on the
dashboard is confusing. This seems to have originally been prevent
deliberately though as the other modules have a not None check. Is
digital takeup a special case? If so the real change should be changing
the transform to ignore only 0s from digital takeup. It's worth noting
that the totals on the services page also ignore 0s (also for digital
takeup?) again. Was this deliberate?
=> Create digital takeup module even when value 0

stagecraft/apps/dashboards/models/module.py
This query parameter was introduced into Backdrop in January 2015
https://github.com/alphagov/backdrop/commit/6f56fa848a59046eb00b0b4893bf8f23e688b08f
Stagecraft has never been updated to allow modules to make use of the
parameter when querying for data. It is very useful for pulling out a
group of keys to then be run through the rate transform.
=> Add filter_by_prefix to query_parameters schema

stagecraft/libs/views/resource.py, stagecraft/libs/views/tests/test_resource.py
At the moment the semantics around deleting a sub resource are not
defined so we should deny this. @jcbashdown
=> Disable deleting a sub_resource

stagecraft/apps/datasets/models/oauth_user.py
When there is an error, we are safe to ignore it, but log this to
statsd. However, counter does not exist as a method name, so this call
fails. Update to incr which does exist
=> Use the correct statsd method name

stagecraft/tools/import_dashboards.py, stagecraft/tools/import_organisations.py, stagecraft/tools/redirects.py, stagecraft/tools/spreadsheets.py, stagecraft/tools/tests/test_import_dashboards.py, stagecraft/tools/tests/test_spreadsheet.py
In the past is was possible this was overridden but response to liz's
notes column in the name spreadsheet. When I made some changes I messed
up further and switched this to liz's notes. It should be neither. tx
spreadsheet is the canonical source of notes on costs.
It looks like it actually was completely correct in import_dashboards (just not elsewhere in the past) until I came in with my big copy and paste. We didn't notice any problem because only import_dashboards uses this field. Not the things I broke earlier.
=> Use tx notes on costs for costs

.travis.yml
Travis support a container based infrastructure for running jobs -
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
This should make builds start faster, and enable us to cache the pip
downloads between jobs, which should speed up builds.
=> Switch to container based infrastructure

stagecraft/apps/datasets/migrations/0005_auto_20150707_1439.py, stagecraft/apps/datasets/models/data_set.py, stagecraft/apps/datasets/tests/models/test_data_set.py, stagecraft/apps/transforms/migrations/0003_auto_20150707_1439.py, stagecraft/apps/transforms/models.py, stagecraft/apps/transforms/tests/test_models.py
Add ability to create datasets and transforms without owners in django admin and forms in general by setting owners field blank property.
Also add tests for this.
https://www.pivotaltracker.com/story/show/97798458
=> Add ability to create datasets and transforms without users.

stagecraft/settings/production.py
Renaming the json log file to production.json.log means that it will get
rotated correctly on gov.uk infrastructure, as it matches the *.log glob
the log rotation uses. It also means it is easy to add a logstream
config for - this isnt currently enabled, but using the filename
production.json.log will make this a simple switch on the govuk::app
defined type in gov.uk puppet This will break logstreaming in the
current infrastructure unless there is a corresponding change in
pp-puppet
=> Update location of json log file

stagecraft/apps/datasets/admin/data_set.py, stagecraft/apps/transforms/admin.py
Add filter-horizontal interface to django admin for datasets and transforms which makes it easier
to add multiple owners, clearer which owners are selected and also possible to remove owners once
added.
=> Allow owners to be removed from datasets and transforms

requirements/_common.txt, stagecraft/apps/collectors/migrations/0001_initial.py, stagecraft/apps/collectors/models.py, stagecraft/apps/collectors/tests/factories.py, stagecraft/apps/collectors/tests/test_models.py, stagecraft/apps/transforms/tests/test_models.py, stagecraft/apps/users/tests/factories.py, stagecraft/settings/common.py, stagecraft/settings/development.py
We have built the underlying data model for collectors in the
Performance Platform.
https://drive.google.com/open?id=0B4BcZ31U-tWQVjZmQVd4UUNXT0t2bXQyQk9pR0RGWUpDUGF3
This uses Fernet to encrypt the credentials we store for 3rd party
services. This is to protect data that has a reasonable impact potential
if leaked when the data is at rest. Fernet uses AES and HMAC under the
hood and should provide adequate protection for our data.
Along side all of the schema tests for the options/query/credentials we
enforce some ownership constraints and some provider constraints. We
want to be sure that a collector uses a type and data source for the
same provider, so we don't end up with a GA collector talking to a Piwik
source. We also want to be sure that the user interacting with the
Collector is …
=> Collectors models and tests

README.md
Since gds/puppet#3159, the gov.uk dev vm defaults to trusty, so we no
longer need to do anything special to make sure we run trusty.
=> Remove guidance on govuk dev vm and trusty

stagecraft/apps/collectors/tests/test_admin.py
Change test for tuples to assert that tuple contatins three items rather than testing content of
tuple as factories do not support querying.
=> Fix collector admin test

stagecraft/apps/collectors/management/commands/import_collector_config.py, stagecraft/apps/collectors/management/commands/import_schemata.py, stagecraft/apps/collectors/migrations/0002_auto_20150730_1328.py, stagecraft/apps/collectors/migrations/0003_auto_20150730_1329.py, stagecraft/apps/collectors/models.py, stagecraft/apps/collectors/schemas/collector-type/ga-contrib-content-table/options.json, stagecraft/apps/collectors/schemas/collector-type/ga-contrib-content-table/query.json, stagecraft/apps/collectors/schemas/collector-type/ga-realtime/options.json, stagecraft/apps/collectors/schemas/collector-type/ga-realtime/query.json, stagecraft/apps/collectors/schemas/collector-type/ga-trending/options.json, stagecraft/apps/collectors/schemas/collector-type/ga-trending/query.json, stagecraft/apps/collectors/schemas/collector-type/ga/options.json, stagecraft/apps/collectors/schemas/collector-type/ga/query.json, stagecraft/apps/collectors/schemas/collector-type/gcloud/options.json, stagecraft/apps/collectors/schemas/collector-type/gcloud/query.json, stagecraft/apps/collectors/schemas/collector-type/pingdom/options.json, stagecraft/apps/collectors/schemas/collector-type/pingdom/query.json, stagecraft/apps/collectors/schemas/collector-type/piwik-core/options.json, stagecraft/apps/collectors/schemas/collector-type/piwik-core/query.json, stagecraft/apps/collectors/schemas/collector-type/piwik-realtime/options.json, stagecraft/apps/collectors/schemas/collector-type/piwik-realtime/query.json, stagecraft/apps/collectors/schemas/collector-type/webtrends-keymetrics/options.json, stagecraft/apps/collectors/schemas/collector-type/webtrends-keymetrics/query.json, stagecraft/apps/collectors/schemas/collector-type/webtrends-reports/options.json, stagecraft/apps/collectors/schemas/collector-type/webtrends-reports/query.json, stagecraft/apps/collectors/tests/factories.py
This sets up a migration for base data (providers, data sources and collector types) then adds a couple of management commands for importing collector type schemas and collector configuration.
Supersedes #399 
This requires https://github.com/alphagov/performanceplatform-collector-config/pull/212 is merged so that the collectors don't fail the schema validation
=> Import collector data

stagecraft/apps/dashboards/tests/views/test_dashboard.py, stagecraft/apps/dashboards/views/dashboard.py
The Department for Communities and Local Government was causing a 500
error because it had other links that were not being serialized
correctly. This fixes that.
=> Fix dashboards with other links

stagecraft/apps/collectors/tests/test_views.py, stagecraft/apps/collectors/views.py, stagecraft/apps/dashboards/views/dashboard.py, stagecraft/apps/dashboards/views/module.py, stagecraft/apps/datasets/views/data_group.py, stagecraft/apps/datasets/views/data_set.py, stagecraft/apps/organisation/views.py, stagecraft/apps/transforms/views.py, stagecraft/apps/users/views.py, stagecraft/libs/views/resource.py, stagecraft/libs/views/tests/test_resource.py, stagecraft/libs/views/utils.py, stagecraft/settings/common.py, stagecraft/urls.py
The views added:
* Provider View
* DataSource View
* CollectorType View
* Collector View
Each view inherits from Resource View and has a schema.
Move common function calls to base ResourceView class
* Moved call to decorator that prohibits caching of results to Resource View.
* Move the call to the add an Authorization header to Resource View.
* Move finding permissions by resource (model) name to ResourceView
The changes will apply to all operations of all views that inherit from Resource View.
https://www.pivotaltracker.com/story/show/99687256
=> Expose collector models (configuration) via an API

stagecraft/libs/request_logger/middleware.py
Now we are on the gov.uk stack we should use the govuk_request_id header
rather than the request_id header we set on our old stack
=> Log the govuk_request_id

requirements/_common.txt, stagecraft/apps/collectors/tests/test_views.py, stagecraft/apps/collectors/views.py
Some of the details required to run a collector are stored in CollectorType.
Too avoid having to make multiple HTTP calls, these details are being
returned by the CollectorView.
CollectorTypeView remains unchanged.
=> Return CollectorType details in Collector View

stagecraft/apps/collectors/models.py, stagecraft/apps/collectors/tests/test_views.py
Models that have an owners attribute need to have a for_user method
defined in the model manager to be able to call list on the models.
Added a Manager for the Collector and DataSource models.
Added tests to check that all of the associated collector models can
be listed if the user is an admin or has the collector permission.
=> Check that collector models can be listed.

stagecraft/apps/datasets/tests/views/test_auth.py, stagecraft/libs/authorization/tests/test_http.py
This will make mocking behave as expected.
There are a couple of cases where we request more than once in a test.
In these cases it is appropriate to store in the db in between requests
also rename duplicate test
=> Delete oauth users between runs

Procfile, requirements/_common.txt, stagecraft/apps/collectors/tasks.py, stagecraft/settings/common.py, stagecraft/settings/development.py
We use django-celery because it provides us with a set of models for
controlling periodic jobs and the scheduler for celerybeat to execute
them.
This adds 3 new process types to the Procfile:
- `worker` the process that will consume the jobs to be executed and
run them. The `-E` tells the process to emit events that will be
consumed by the celerycam process to store state of jobs
- `beat` reads from the database and triggers scheduled periodic jobs
- `celerycam` reads the state of running jobs periodically and stores
this information in the database
=> Add celery job queue to Stagecraft

stagecraft/apps/collectors/schemas/collector-type/ga-contrib-content-table/options.json, stagecraft/apps/collectors/schemas/collector-type/ga/options.json, stagecraft/apps/collectors/schemas/collector-type/piwik-core/options.json, stagecraft/apps/collectors/schemas/collector-type/piwik-realtime/options.json, stagecraft/apps/collectors/schemas/collector-type/webtrends-keymetrics/options.json, stagecraft/apps/collectors/schemas/collector-type/webtrends-reports/options.json
Allow a parameter to be added to options in the collector conifg
that instructs collectors to purge the contents of dataset everytime
it collects more data.
See: https://github.com/alphagov/performanceplatform-collector/pull/132
Pivotal: https://www.pivotaltracker.com/story/show/100818900
=> Add option to empty-data-set to GA collector schema

stagecraft/apps/collectors/schemas/collector-type/ga-trending/options.json
When we ran the migration scripts to import the collector config into
stagecraft we realised some fields had been missed in the schemas.
=> Add missing elements to schemas

Procfile
Although manage.py seemed to indicate that it would load settings based
of the --settings flag, this doesn't seem to work. This switches the
flag for an environment variable that does work.
=> Use environment variable rather than --settings

Procfile
It turned out that the problem with --settings was that it needs to come
after the command that manage.py will execute, not before. I've tested
this in the dev vm and it seems to work.
=> exec doesn't support inline environment variables

Procfile
It mistakes this for the command you are trying to run and if you switch
to `celery beat` with the --settings after it will complain that
--settings is not an expected option. Luckily they have a couple of
other commands that alais to the two part commands that do work.
=> Celery doesn't support the --settings

.travis.yml, requirements/_common.txt
Se we can integrate the collectors with stagecraft, and use
django-celery to schedule them to run instead of relying on a series of
cronjobs
=> Add latest performanceplatform-collector

stagecraft/libs/backdrop_client/backdrop_client.py
BACKDROP_URL has been deprecated in favour of specifying the read or
write url directly so that we stay within gov.uk infrastructure and do
not route internal requests via the internet. This needs updating for
the delete endpoint.
=> Use write url instead of generic backdrop url

stagecraft/apps/collectors/models.py, stagecraft/apps/collectors/tasks.py, stagecraft/apps/collectors/tests/test_tasks.py, stagecraft/settings/common.py
Use Celery periodic tasks to run collectors rather than a crontab file.
Note - Two tasks are defined in this pull request, one for Google Analytics and Piwik realtime tasks (run every 5 minutes) and one for all other collectors (run at midnight each day).
Story: https://www.pivotaltracker.com/story/show/100638186
=> Run collectors periodically using Celery

stagecraft/settings/common.py
We don't want to run all collectors using Celery periodic tasks to begin with. Rather we want
to first confirm that real-time collectors run okay.
Note - merge/release at the same time as https://github.com/alphagov/performanceplatform-collector-config/pull/235
=> Suppress non-realtime collector jobs

stagecraft/apps/collectors/tasks.py, stagecraft/settings/common.py
When running from cron, collectors were disabled from running on preview
and staging due to google api rate limits. This setting will let us
disable the collectors on staging and preview.
=> Add a setting to disable collectors

stagecraft/settings/common.py
After successfully running realtime collectors using Celery periodic tasks, we now want to run all collectors using this approach.
=> Run all collectors as Celery periodic tasks

stagecraft/settings/common.py
The hourly Celery periodic tasks were not running due to a missing comma in the settings. This might also have caused the daily tasks not to run.
=> Fix Celery periodic tasks settings

requirements/_common.txt, stagecraft/apps/collectors/tasks.py
When running collectors via Stagecraft, log all collector output to /log directory, rather than the /log directory of performanceplatform-collector.
Story: https://www.pivotaltracker.com/story/show/105753440
=> Route collector logging to /log

stagecraft/apps/datasets/admin/data_set.py, stagecraft/apps/datasets/models/data_set.py, stagecraft/apps/datasets/tests/models/test_data_set.py
Remove config and validation that prevents the capped_size field on DataSet from being changed in Django Admin after a data set has been created.
Story: https://www.pivotaltracker.com/story/show/95028694
=> Make capped_size field on DataSet editable

stagecraft/apps/collectors/admin.py, stagecraft/apps/organisation/admin.py, stagecraft/apps/transforms/admin.py
Order Datasources by slug in django admin.
Order Nodes (Organisations) by name in django admin
Add search filter to Transforms in Django Admin
Allow filtering by:
* input data group
* input data type
* output data group
* output data type
Add ordering to Transforms on Django Admin
Display Transforms in the following order
1. input group
2. input type
3. output group
4. output type
Pivotal: https://www.pivotaltracker.com/story/show/95028568
=> Display content of lists and menus in alphabetical order

requirements/_common.txt
Get the latest version of the performance platform collector library so as to start rotating log files. See https://github.com/alphagov/performanceplatform-collector/pull/142
=> Bump performance platform collector library

requirements/_common.txt
Version 0.2.8 contains code to release logging resources which will hopefully resolve an issue in production where file descriptors for log files are not being released after a collector is run.
=> Bump performanceplatform-collector library to 0.2.8

stagecraft/apps/datasets/models/data_set.py, stagecraft/apps/datasets/views/data_set.py, stagecraft/apps/users/admin.py, stagecraft/apps/users/management/commands/import_users_from_backdrop.py, stagecraft/apps/users/tests/management/commands/test_import_users_from_backdrop.py
Enable the adding of data sets from the user admin form in Django Admin.
Story: https://www.pivotaltracker.com/story/show/100714550
=> Extend user admin form to assign data sets

stagecraft/settings/common.py
Use the crontab function rather than the timedelta when scheduling collector tasks so that the realtime jobs run at 5 mins, 10 mins etc past the hour and the hourly jobs run on the hour, rather than relative to when the celery beat worker was last re-started.
NOTE - The celery beat worker will need to be manually re-started when releasing this change. See celerycam command in the Procfile
=> Replace timedelta with crontab in task scheduling

stagecraft/apps/dashboards/admin/dashboard.py, stagecraft/apps/dashboards/models/dashboard.py
Other links, to things like policies and publications are not
editable in performanceplatform-admin. It seems that these links were
added to some of the site activity dashboards in the early days of
performance platform, when the config for dashboards was stored in as
json files in the spotlight-config repo.
The contents of spotlight-config was then migrated to stagecraft using the
spotlight_config_migration script. This script is the only place I could find
where links are actively added to dashboards.
It is possible to add other links to a dashboard by using the stagecraft api,
but as they are not included in the post data from performanceplatform-admin,
it can be assumed that these links are no longer supported.
A zendesk ticket was raised recently because to the link to the …
=> Make Link model editable in Django Admin

stagecraft/apps/dashboards/models/dashboard.py, stagecraft/apps/dashboards/models/module.py, stagecraft/apps/datasets/admin/data_set.py, stagecraft/apps/datasets/models/data_set.py, stagecraft/apps/datasets/static/admin/css/datasets.css, stagecraft/apps/datasets/templates/data_set/change_form.html, stagecraft/apps/datasets/tests/admin/test_data_set.py, stagecraft/apps/datasets/tests/models/test_data_set.py, stagecraft/apps/organisation/models.py, stagecraft/apps/organisation/views.py
Stagecraft should be able to determine whether a dataset is used in a published or unpublished dashboard and whether 'orphaned'. Default behaviour is that only orphaned datasets can be deleted. Override should be allowable to datasets in unpublished dashboards to be deleted. datasets used in published dashboards must not be able to be deleted.
Added a check on the django admin change form for the data set. If the dataset is linked to a dashboard that is published, the delete data set button is disabled, and a list of linked dashboards is displayed to the user.
Pivotal: https://www.pivotaltracker.com/story/show/95029022
=> Disable dataset delete

stagecraft/tools/fixtures/tx.json, stagecraft/tools/fixtures/tx_no_agency_abbr.json, stagecraft/tools/spreadsheets.py
The short service name and description 2 columns have been removed
from the source spreadsheet for transactions explorer. Adapted the
code to reflect the new column positions.
=> Transaction Explorer spreadsheet column changes

stagecraft/tools/README.md
Add instructions about how to link transactions explorer dashboards to an organisation.
=> Add import_organisations script to README

requirements/_common.txt
The performanceplatform-collector library has been updated to fix a bug with the generation of credentials (see story: https://www.pivotaltracker.com/story/show/111132054).
=> Bump performanceplatform-collector to 0.3.0

stagecraft/tools/import_organisations.py
Abbreviations longer than 50 characters in length cause the
import_organisations script to fail.
In the Node (organisation) model, the abbreviation field is limited
to 50 characters.
When the model is serialized or made ready for spotlight, if an
abbreviation does not exist, the name is passed back instead.
The name field allows upto 256 characters.
Have updated the import_organisations script until it is determined
whether of not it is safe to update the Node model.
Pivotal: https://www.pivotaltracker.com/story/show/110412434
=> Abbreviations longer than 50 characters cause import to fail

stagecraft/tools/import_organisations.py
The Dashboard model used to limit the size of the slug to 90 characters.
This limit was changed to 1000 characters a while ago to accomodate the
slugs for BIS dashboards.
The import organisation script has been updated to reflect the change in
slug size.
=> Remove slug truncation from import_organisations script

stagecraft/tools/spreadsheets.py
The Dashboard model used to limit the size of the slug to 90 characters.
This limit was changed to 1000 characters a while ago to accomodate the
slugs for BIS dashboards.
The import dashboards script has been updated to reflect the change in
slug size.
=> Remove slug truncation from import_dashboards script

stagecraft/apps/dashboards/tests/views/test_dashboard.py, stagecraft/apps/datasets/tests/support/test_helpers.py, stagecraft/libs/views/utils.py
The Error JSON used return a status of 'error' and nest the status code
further in the message. This causes problems for Kibana/Elastic Search
which expects the status field to contain a numerical status code.
=> Return the HTTP status code in the error

stagecraft/tools/README.md
The SUMMARIES_URL environment variable should point to the data set in Backdrop that contains the imported data from Transactions Explorer.
=> Correct SUMMARIES_URL environment variable

stagecraft/apps/dashboards/admin/dashboard.py
Stagecraft has two ways of returning the organisations that a dashboard
is linked to through its public API:
- https://stagecraft.production.performance.service.gov.uk/public/dashboards
- https://stagecraft.production.performance.service.gov.uk/public/dashboards?slug=bis-online-registration-to-participate-in-ukti-events
1. If the API is called without a slug, a method in the Dashboard view is called to return the
config for every published dashboard. This method gets the organisations
associated to the dashboard from the pre-filled "cache" database fields, e.g.
department_cache, agency_cache etc. This is how the department field is populated
on the services page rendered by Spotlight.
2. If the API is passed a dashboard slug, a different method in the Dashboard view is called
to get the …
=> Expose cache values

stagecraft/apps/dashboards/admin/dashboard.py
Reverts alphagov/stagecraft#462
These changes are not needed.  The "cache" values are updated when the dashboard saved in the Admin app.
=> Revert "Expose cache values"

stagecraft/tools/import_organisations.py
This is required due to a new organisation (Ad-hoc advisory group) being added to the organisations api on 28th June 2016.
=> Add new organisation mapping

requirements/_common.txt, stagecraft/tools/import_organisations.py
The department BIS no longer exists so mapping Research Councils to BEIS.
Also taking the opportunity to bump performanceplatform-collector library to latest version 0.3.1.
=> Fix dept mapping

stagecraft/settings/production.py
In the last 24 hours, Stagecraft in production has logged 3.7 million of the 24 million log lines across all of GOV.UK. All but 614 of these are at INFO level, so setting the threshold to WARNING should remove the vast majority of our unnecessary logs in production.
https://docs.djangoproject.com/en/1.8/topics/logging/
=> Reduce log level in production

.travis_scripts/push_release_tag.sh
Send `stdout` and `stderr` output to dev null so it does not appear in CI logs. If git push errors over https the output includes the GH auth token.
=> Silence output on push

stagecraft/settings/production.py
Logging handler class was changed for latest Django version
=> Change LOGGING.handlers in production settings

etc/deploy.sh, manifest.yml
there is a regular (not user provided) redis in staging and production.
this should be bound to the service but the credentials parsing code
will still use the old redis (redis-poc) so this is effectively a no-op
solo @tlwr
=> bind new redis

etc/deploy.sh, manifest.yml
Update the manifest to remove the deprecation warnings. Remove the now redundant lines from the deploy.sh script.
=> Free manifest of deprecation warnings.

.travis.yml, etc/deploy.sh
Add the basic auth secrets to the travis script so they can be correctly injected at deploy time.
=> Add the FLOWER_BASIC_AUTH secrets for staging and production to travis.

etc/deploy.sh
The problem is caused by "split brain" environment variables. Where some
are set in the manifest and some in the deploy script some are getting
missed by a `cf start`. Presumably a `--no-start` doesn't push up the
environment variables.
=> Push, rather than start, the app after set-env.

etc/deploy.sh, manifest.yml
Between 6.36 and 6.38 of cf-cli the behaviour of yaml anchors, specifically
relating to `env` regressed so it no longer picks up the "common" ones.
=> Fix regression in cf handling of yaml anchors.

README.md
Stagecraft was removed from `govuk-puppet`, so it no longer works with the GOV.UK VM.
Ref:
- https://github.com/alphagov/govuk-puppet/pull/6720
- https://github.com/alphagov/govuk-puppet/pull/6732
- https://github.com/alphagov/govuk-puppet/pull/6742
=> Remove GOV.UK VM stuff from the README.

etc/deploy.sh
For consistency we now deploy using a concourse pipeline, to enable this to work the following changes have been made to the deploy script.
Two variables are no longer required. We no longer need to download the cf cli, as concourse will take care of this for us. To prevent us from having to chmod the deploy script on each deploy this has been saved as an executable.
Single: @matthewcullum-gds
=> Change deploy for concourse

requirements/_common.txt
Richard Towers has found that you can pip install this with our buildpack and it works. This is probably because it includes the compiled binaries in a wheel instead of requiring us to build them out of tar.gz.
=> Bump cryptography package version

requirements/_common.txt
Otherwise pyOpenSSL freaks out and everything, including listing dashboards in the admin UI, breaks.
```
[23-Jul-19 09:14:06] ERROR [django.request:135] Internal Server Error: /data-sets
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
...
File "/home/vcap/deps/0/python/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
conn.connect()
File "/home/vcap/deps/0/python/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 333, in connect
cert = self.sock.getpeercert()
File "/home/vcap/deps/0/python/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 343, in …
```
=> Add idna dependency
