alphagov/stagecraft

stagecraft/apps/dashboards/migrations/0010_consistent_group_by_list_for_tabs.py
stagecraft/apps/dashboards/models/module.py
stagecraft/apps/dashboards/tests/models/test_module.py

- Data migration for existing data
- Custom validation to rewrite any new input to be in the new,
consistent format
See See https://www.agileplannerapp.com/boards/15088/cards/9043

Update group_by for tabs to always be a list

---

initial_transform_creation.py

- Some dashboards use the same dataset and module name, so we need to
include the dashboard slug in these. For ease of implementation this is
currently a list of dashboards that need this behaviour
- No longer try to run the transform for empty datasets
- Skip already migrated dashboards, and some temporary dashboards
- add some logging and switch from print statements to using logger

Transform remaining dashboards

---

initial_transform_creation.py
stagecraft/apps/datasets/migrations/0015_auto__chg_field_datagroup_name.py
stagecraft/apps/datasets/models/data_group.py

This makes it easier to trace datasets back to dashboards for building the
organisation api.

Change name of datagroup rather than datatype

---

run_initial_services_page_transformation.py
stagecraft/apps/transforms/models.py
stagecraft/apps/transforms/views.py

This will create the latest-data transform for the services page, and run
it against all datasets with those datatypes.

Script to create and run service page migrations

---

stagecraft/apps/datasets/migrations/0016_cap_realtime.py
tools/cap_uncapped.js

This doesnt actually do anything other than mark them as capped in the admin
interface, but it seemed best to be complete.
To actually cap the collection, we need to run the added mongo script

Script to update uncapped realtime datasets

---

.travis.yml

backdrop already does this - it wastes time in the build queue

Dont build deployed-to branches

---

stagecraft/apps/organisation/models.py
stagecraft/apps/organisation/views.py

- After consultation with Matt - we generally need it and it's much
faster.

Always select_related('typeOf') for nodes

---

stagecraft/apps/datasets/tests/views/test_auth.py
stagecraft/apps/datasets/views/auth.py

Return a 204 with no content for non-JSON response

---

stagecraft/apps/dashboards/models/dashboard.py
stagecraft/apps/organisation/migrations/0004_auto__del_unique_node_abbreviation__chg_field_node_slug.py
stagecraft/apps/organisation/migrations/0005_auto__del_unique_node_name__add_unique_node_name_slug_typeOf.py
stagecraft/apps/organisation/models.py
stagecraft/apps/organisation/tests/test_models.py
stagecraft/tools/import_dashboards.py
stagecraft/tools/import_organisations.py

And Fix module creation. This replaces #332

Add import organizations script

---

doc/arch/adr-001.md

Explain how we will provide a security model for organisations,
dashboards and datasets.

Security Architecture Decision Record

---

stagecraft/apps/dashboards/tests/views/test_module.py
stagecraft/apps/dashboards/views/module.py
stagecraft/urls.py

Block posting for now.
This is required to make cloning modules a bit more efficient.

Enable get module directly with resource view

---

stagecraft/tools/redirects.py
stagecraft/tools/tests/test_redirect_generation.py

Also do not follow 301s - this hides them.

Fix redirects - naked domain always redirects.

---

stagecraft/apps/dashboards/tests/views/test_dashboard.py
stagecraft/apps/dashboards/tests/views/test_module.py
stagecraft/apps/dashboards/views/dashboard.py
stagecraft/apps/organisation/tests/test_views.py
stagecraft/libs/authorization/http.py
stagecraft/libs/authorization/tests/test_http.py
stagecraft/libs/views/resource.py
stagecraft/libs/views/tests/test_resource.py
stagecraft/settings/common.py

Add delete method, and permissions.  Add tests for deleting a dashboard and remove tests which assert that delete method doesn't exist.

Add delete method and tests.

---

stagecraft/apps/collectors/admin.py
stagecraft/apps/collectors/models.py
stagecraft/apps/collectors/static/admin/js/filterselect.js
stagecraft/apps/collectors/tests/factories.py
stagecraft/apps/collectors/tests/test_admin.py

Add filters to data source based on provider type, by overriding select widget, data source and
type fields in django admin.

Add filtering to collectors in django admin for onboarding.

---

stagecraft/apps/datasets/tests/views/test_data_set.py
stagecraft/libs/authorization/http.py
stagecraft/libs/views/resource.py
stagecraft/libs/views/tests/test_resource.py
stagecraft/settings/common.py

Includes a comment to explain some behaviour and deleting a duplicate test.

Allow collector view without owning for omniscient

---

requirements/_common.txt
stagecraft/__init__.py
stagecraft/apps/collectors/libs/ga.py
stagecraft/apps/collectors/libs/tests/test_ga.py
stagecraft/apps/collectors/models.py
stagecraft/apps/collectors/tasks.py
stagecraft/apps/collectors/tests/test_tasks.py
stagecraft/apps/collectors/tests/test_views.py
stagecraft/apps/collectors/views.py
stagecraft/celery.py
stagecraft/libs/views/resource.py
stagecraft/urls.py

Allow the running of collectors through Stagecraft using collector config and credentials stored in the Stagecraft DB:
- Store config information about each collector and the credentials (credentials) needed to run each type of collector in the Stagecraft DB;
- Expose an endpoint to trigger the running of a collector (each collector is identified by a unique slug extracted from the called endpoint);
- When the endpoint is called, retrieve the config information for the collector and the necessary credentials, and create a Celery task to run the collector (using the _run_collector method in collector/main.py in the performanceplatform-collector repo), passing the credentials, config and other runtime arguments such as start and end date.
Note - Before running a Google Analytics collector, …

Run collector endpoint and task

---

requirements/_common.txt
stagecraft/apps/collectors/admin.py
stagecraft/apps/collectors/tasks.py
stagecraft/apps/collectors/tests/test_views.py
stagecraft/apps/collectors/views.py

*Background*
The story asks for functionality in django admin for the onboarding team to run collector.
They can't curl the endpoint from the command line as to do that, you need the bearer token, and that is hard to get a hold of in production.
The first thought I had was to add a button the the end of each collector row that when clicked executes the collector.
Initially I attempted to do this using a html link to call the view, but this ran into same problem as curling the endpoint, no bearer token.
Then I looked into calling the run_collector task directly from the button.  This had other problems: You can't call a python method from an html form, it needs to wrapped in javascript. Then I started investigating whether it could be done using Ajax to call the python method from …

Run collector from admin screen

---

.gitignore
requirements/_common.txt

Use v0.2.7 of performanceplatform-collector so as to pick up the changeover from RotatingFileHandler to ConcurrentLogHandler.

Bump performanceplatform-collector library

---

stagecraft/apps/dashboards/views/dashboard.py
stagecraft/settings/development.py
stagecraft/settings/production.py

See commit messages for more details.

Add non-secret production config

---

requirements/_common.txt
stagecraft/apps/collectors/models.py
tools/replicate-db.sh

See https://github.com/alphagov/stagecraft/issues/467

Bump cryptography library and fix replicate-db script

---

stagecraft/settings/production.py

This reverts commit 089882e9d7cd7b296108749d2491ae7562ec0a38.
For some reason this doesn't work.

Revert "Add database and message queue config for prod"

---

stagecraft/settings/production.py

Load FERNET_USE_HKDF and FERNET_KEYS from environmental variables.

Add environmental variables

---

requirements/_common.txt

Release notes: https://docs.djangoproject.com/en/1.11/releases/1.11.1/

Upgrade django to 1.11.1

---

stagecraft/apps/collectors/admin.py
stagecraft/apps/collectors/tests/test_admin.py

UUID field representation changed in django admin and broke existing
implementation.

Fix collector type field

---

stagecraft/tools/import_organisations.py

land registry abbreviation field changed in organisations api and we needed to cover this case in mapping of data

Cover another edge case in govuk_node_for_record

---

stagecraft/apps/datasets/admin/data_set.py
stagecraft/apps/datasets/templates/data_set/change_form.html
stagecraft/apps/datasets/tests/admin/test_data_set.py
stagecraft/apps/datasets/tests/factories.py

Added confirmation message is an extra step to prevent harmful things from happening

Admin - empty data set confirmation

---

manifest.yml

And set max_in_flight to one less so we have less downtime

Update number of stagecraft-web instances

---

manifest.yml

Update to shared `logit-ssl-drain`

update logit service name

---

manifest.yml

merge master changes

---

etc/run_flower.sh
manifest.yml
requirements/_common.txt
stagecraft/settings/common.py
stagecraft/settings/rediss.py

Adds support for TLS-enabled redis.

Migrate to rediss (redis with TLS).

---

etc/deploy.sh

Due to issues with caching and environment variable requirements inside the application and no really sensible way to inject the secrets...we have...

"Improved" the deployment so it doesn't always fail.

---

stagecraft/tools/spreadsheets.py

A new year has been added. This means a bunch of our magic offsets have
been increased by four—once for every quarter.

Update column indexes
